# Supabase Configuration
project_id = "YOUR_PROJECT_REF"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true

[functions]
# No settings needed for basic setup
