import type { Meta, StoryObj } from '@storybook/react';
import AwardShowcase from './AwardShowcase';
import type { GameWithRanking } from '@/types';

const meta = {
  title: 'Components/Features/Awards/AwardShowcase',
  component: AwardShowcase,
  parameters: {
    layout: 'padded',
    docs: {
      description: {
        component: 'Complete award category display showing winner and nominees in a clean, organized layout.',
      },
    },
  },
  tags: ['autodocs'],
} satisfies Meta<typeof AwardShowcase>;

export default meta;
type Story = StoryObj<typeof meta>;

// Mock complete award data
const mockAwardGames: GameWithRanking[] = [
  // Winner (first in array)
  {
    id: '1',
    name: 'Wingspan',
    image_url: 'https://via.placeholder.com/150x150?text=Wingspan',
    bgg_id: 266192,
    year_published: 2019,
    min_players: 1,
    max_players: 5,
    playtime_minutes: 70,
    publisher: 'Stonemaier Games',
    description: 'Build bird habitats and collect birds in this beautiful engine-building game.',
    categories: ['Animals', 'Card Game'],
    mechanics: ['Engine Building', 'Card Drafting'],
    rank: 1,
    rating: 8.2,
    num_ratings: 15000,
    thumbnail_url: null,
    summary: null,
    cached_at: null,
    created_at: '2023-01-01',
    updated_at: '2023-01-01',
    ranking: {
      id: '1',
      user_id: 'user1',
      game_id: '1',
      played_it: true,
      ranking: 9,
      notes: null,
      public_note: null,
      private_note: null,
      created_at: '2023-01-01',
      imported_from: null,
      updated_at: '2023-01-01',
    },
  },
  // Nominees
  {
    id: '2',
    name: 'Azul',
    image_url: 'https://via.placeholder.com/150x150?text=Azul',
    bgg_id: 230802,
    year_published: 2017,
    min_players: 2,
    max_players: 4,
    playtime_minutes: 45,
    publisher: 'Plan B Games',
    description: 'Create beautiful tile patterns inspired by Portuguese azulejos.',
    categories: ['Abstract Strategy'],
    mechanics: ['Pattern Building', 'Tile Placement'],
    rank: 2,
    rating: 7.8,
    num_ratings: 12000,
    thumbnail_url: null,
    summary: null,
    cached_at: null,
    created_at: '2023-01-01',
    updated_at: '2023-01-01',
    ranking: {
      id: '2',
      user_id: 'user1',
      game_id: '2',
      played_it: true,
      ranking: 8,
      notes: null,
      public_note: null,
      private_note: null,
      created_at: '2023-01-01',
      imported_from: null,
      updated_at: '2023-01-01',
    },
  },
  {
    id: '3',
    name: 'Scythe',
    image_url: 'https://via.placeholder.com/150x150?text=Scythe',
    bgg_id: 169786,
    year_published: 2016,
    min_players: 1,
    max_players: 5,
    playtime_minutes: 115,
    publisher: 'Stonemaier Games',
    description: 'Lead your faction to victory in this asymmetric strategy game.',
    categories: ['Science Fiction', 'Territory Building'],
    mechanics: ['Area Control', 'Variable Player Powers'],
    rank: 3,
    rating: 8.3,
    num_ratings: 18000,
    thumbnail_url: null,
    summary: null,
    cached_at: null,
    created_at: '2023-01-01',
    updated_at: '2023-01-01',
    ranking: {
      id: '3',
      user_id: 'user1',
      game_id: '3',
      played_it: true,
      ranking: 7,
      notes: null,
      public_note: null,
      private_note: null,
      created_at: '2023-01-01',
      imported_from: null,
      updated_at: '2023-01-01',
    },
  },
];

export const Default: Story = {
  args: {
    id: 'best-strategy',
    title: 'Best Strategy Game',
    description: 'Games that provide deep strategic thinking and decision-making.',
    games: mockAwardGames,
  },
};

export const WinnerOnly: Story = {
  args: {
    id: 'game-of-year',
    title: 'Game of the Year',
    description: 'The standout game that defined this year.',
    games: [mockAwardGames[0]], // Only winner, no nominees
  },
};

export const ManyNominees: Story = {
  args: {
    id: 'best-strategy-expanded',
    title: 'Best Strategy Game - Expanded Field',
    description: 'A competitive category with many excellent nominees.',
    games: [
      mockAwardGames[0], // Winner
      ...mockAwardGames.slice(1), // Original nominees
      // Add more nominees to test scrolling
      {
        id: '4',
        name: 'Terraforming Mars',
        image_url: 'https://via.placeholder.com/150x150?text=TM',
        bgg_id: 167791,
        year_published: 2016,
        min_players: 1,
        max_players: 5,
        playtime_minutes: 120,
        publisher: 'FryxGames',
        description: 'Transform Mars into a habitable planet.',
        categories: ['Economic', 'Science Fiction'],
        mechanics: ['Card Drafting', 'Tile Placement'],
        rank: 4,
        rating: 8.4,
        num_ratings: 20000,
        thumbnail_url: null,
        summary: null,
        cached_at: null,
        created_at: '2023-01-01',
        updated_at: '2023-01-01',
        ranking: null,
      },
      {
        id: '5',
        name: 'Gloomhaven',
        image_url: 'https://via.placeholder.com/150x150?text=GH',
        bgg_id: 174430,
        year_published: 2017,
        min_players: 1,
        max_players: 4,
        playtime_minutes: 120,
        publisher: 'Cephalofair Games',
        description: 'Tactical combat in a persistent world.',
        categories: ['Adventure', 'Fantasy'],
        mechanics: ['Hand Management', 'Campaign'],
        rank: 5,
        rating: 8.7,
        num_ratings: 25000,
        thumbnail_url: null,
        summary: null,
        cached_at: null,
        created_at: '2023-01-01',
        updated_at: '2023-01-01',
        ranking: null,
      },
      {
        id: '6',
        name: '7 Wonders Duel',
        image_url: 'https://via.placeholder.com/150x150?text=7WD',
        bgg_id: 173346,
        year_published: 2015,
        min_players: 2,
        max_players: 2,
        playtime_minutes: 30,
        publisher: 'Repos Production',
        description: 'Two-player civilization building.',
        categories: ['Ancient', 'Card Game'],
        mechanics: ['Card Drafting', 'Set Collection'],
        rank: 6,
        rating: 8.1,
        num_ratings: 15000,
        thumbnail_url: null,
        summary: null,
        cached_at: null,
        created_at: '2023-01-01',
        updated_at: '2023-01-01',
        ranking: null,
      },
      {
        id: '7',
        name: 'Pandemic Legacy',
        image_url: 'https://via.placeholder.com/150x150?text=PL',
        bgg_id: 161936,
        year_published: 2015,
        min_players: 2,
        max_players: 4,
        playtime_minutes: 60,
        publisher: 'Z-Man Games',
        description: 'Cooperative legacy game about saving the world.',
        categories: ['Medical', 'Cooperative'],
        mechanics: ['Cooperative Play', 'Legacy'],
        rank: 7,
        rating: 8.6,
        num_ratings: 18000,
        thumbnail_url: null,
        summary: null,
        cached_at: null,
        created_at: '2023-01-01',
        updated_at: '2023-01-01',
        ranking: null,
      },
      {
        id: '8',
        name: 'Spirit Island',
        image_url: 'https://via.placeholder.com/150x150?text=SI',
        bgg_id: 162886,
        year_published: 2017,
        min_players: 1,
        max_players: 4,
        playtime_minutes: 90,
        publisher: 'Greater Than Games',
        description: 'Defend your island from colonizing invaders.',
        categories: ['Fantasy', 'Cooperative'],
        mechanics: ['Area Control', 'Variable Player Powers'],
        rank: 8,
        rating: 8.3,
        num_ratings: 16000,
        thumbnail_url: null,
        summary: null,
        cached_at: null,
        created_at: '2023-01-01',
        updated_at: '2023-01-01',
        ranking: null,
      },
      {
        id: '9',
        name: 'Brass: Birmingham',
        image_url: 'https://via.placeholder.com/150x150?text=BB',
        bgg_id: 224517,
        year_published: 2018,
        min_players: 2,
        max_players: 4,
        playtime_minutes: 120,
        publisher: 'Roxley',
        description: 'Industrial revolution economic strategy.',
        categories: ['Economic', 'Industry'],
        mechanics: ['Network Building', 'Hand Management'],
        rank: 9,
        rating: 8.5,
        num_ratings: 14000,
        thumbnail_url: null,
        summary: null,
        cached_at: null,
        created_at: '2023-01-01',
        updated_at: '2023-01-01',
        ranking: null,
      },
      {
        id: '10',
        name: 'Great Western Trail',
        image_url: 'https://via.placeholder.com/150x150?text=GWT',
        bgg_id: 193738,
        year_published: 2016,
        min_players: 2,
        max_players: 4,
        playtime_minutes: 75,
        publisher: 'Stronghold Games',
        description: 'Deliver cattle across the American frontier.',
        categories: ['Economic', 'Animals'],
        mechanics: ['Deck Building', 'Hand Management'],
        rank: 10,
        rating: 8.2,
        num_ratings: 13000,
        thumbnail_url: null,
        summary: null,
        cached_at: null,
        created_at: '2023-01-01',
        updated_at: '2023-01-01',
        ranking: null,
      },
      {
        id: '11',
        name: 'Food Chain Magnate',
        image_url: 'https://via.placeholder.com/150x150?text=FCM',
        bgg_id: 175914,
        year_published: 2015,
        min_players: 2,
        max_players: 5,
        playtime_minutes: 120,
        publisher: 'Splotter Spellen',
        description: 'Build a fast food chain empire.',
        categories: ['Economic', 'Industry'],
        mechanics: ['Hand Management', 'Modular Board'],
        rank: 11,
        rating: 8.1,
        num_ratings: 11000,
        thumbnail_url: null,
        summary: null,
        cached_at: null,
        created_at: '2023-01-01',
        updated_at: '2023-01-01',
        ranking: null,
      },
    ],
  },
};

export const DesktopOptimal: Story = {
  args: {
    id: 'best-strategy-desktop',
    title: 'Best Strategy Game - Desktop View',
    description: 'Optimized layout showing winner prominence with efficient nominee display.',
    games: [
      mockAwardGames[0], // Winner
      ...mockAwardGames.slice(1), // 2 original nominees
      // Add exactly 8 more for nice 10-nominee grid
      {
        id: '4',
        name: 'Terraforming Mars',
        image_url: 'https://via.placeholder.com/150x150?text=TM',
        bgg_id: 167791,
        year_published: 2016,
        min_players: 1,
        max_players: 5,
        playtime_minutes: 120,
        publisher: 'FryxGames',
        description: 'Transform Mars into a habitable planet.',
        categories: ['Economic', 'Science Fiction'],
        mechanics: ['Card Drafting', 'Tile Placement'],
        rank: 4,
        rating: 8.4,
        num_ratings: 20000,
        thumbnail_url: null,
        summary: null,
        cached_at: null,
        created_at: '2023-01-01',
        updated_at: '2023-01-01',
        ranking: null,
      },
      {
        id: '5',
        name: 'Gloomhaven',
        image_url: 'https://via.placeholder.com/150x150?text=GH',
        bgg_id: 174430,
        year_published: 2017,
        min_players: 1,
        max_players: 4,
        playtime_minutes: 120,
        publisher: 'Cephalofair Games',
        description: 'Tactical combat in a persistent world.',
        categories: ['Adventure', 'Fantasy'],
        mechanics: ['Hand Management', 'Campaign'],
        rank: 5,
        rating: 8.7,
        num_ratings: 25000,
        thumbnail_url: null,
        summary: null,
        cached_at: null,
        created_at: '2023-01-01',
        updated_at: '2023-01-01',
        ranking: null,
      },
      {
        id: '6',
        name: '7 Wonders Duel',
        image_url: 'https://via.placeholder.com/150x150?text=7WD',
        bgg_id: 173346,
        year_published: 2015,
        min_players: 2,
        max_players: 2,
        playtime_minutes: 30,
        publisher: 'Repos Production',
        description: 'Two-player civilization building.',
        categories: ['Ancient', 'Card Game'],
        mechanics: ['Card Drafting', 'Set Collection'],
        rank: 6,
        rating: 8.1,
        num_ratings: 15000,
        thumbnail_url: null,
        summary: null,
        cached_at: null,
        created_at: '2023-01-01',
        updated_at: '2023-01-01',
        ranking: null,
      },
      {
        id: '7',
        name: 'Pandemic Legacy',
        image_url: 'https://via.placeholder.com/150x150?text=PL',
        bgg_id: 161936,
        year_published: 2015,
        min_players: 2,
        max_players: 4,
        playtime_minutes: 60,
        publisher: 'Z-Man Games',
        description: 'Cooperative legacy game about saving the world.',
        categories: ['Medical', 'Cooperative'],
        mechanics: ['Cooperative Play', 'Legacy'],
        rank: 7,
        rating: 8.6,
        num_ratings: 18000,
        thumbnail_url: null,
        summary: null,
        cached_at: null,
        created_at: '2023-01-01',
        updated_at: '2023-01-01',
        ranking: null,
      },
      {
        id: '8',
        name: 'Spirit Island',
        image_url: 'https://via.placeholder.com/150x150?text=SI',
        bgg_id: 162886,
        year_published: 2017,
        min_players: 1,
        max_players: 4,
        playtime_minutes: 90,
        publisher: 'Greater Than Games',
        description: 'Defend your island from colonizing invaders.',
        categories: ['Fantasy', 'Cooperative'],
        mechanics: ['Area Control', 'Variable Player Powers'],
        rank: 8,
        rating: 8.3,
        num_ratings: 16000,
        thumbnail_url: null,
        summary: null,
        cached_at: null,
        created_at: '2023-01-01',
        updated_at: '2023-01-01',
        ranking: null,
      },
      {
        id: '9',
        name: 'Brass: Birmingham',
        image_url: 'https://via.placeholder.com/150x150?text=BB',
        bgg_id: 224517,
        year_published: 2018,
        min_players: 2,
        max_players: 4,
        playtime_minutes: 120,
        publisher: 'Roxley',
        description: 'Industrial revolution economic strategy.',
        categories: ['Economic', 'Industry'],
        mechanics: ['Network Building', 'Hand Management'],
        rank: 9,
        rating: 8.5,
        num_ratings: 14000,
        thumbnail_url: null,
        summary: null,
        cached_at: null,
        created_at: '2023-01-01',
        updated_at: '2023-01-01',
        ranking: null,
      },
      {
        id: '10',
        name: 'Great Western Trail',
        image_url: 'https://via.placeholder.com/150x150?text=GWT',
        bgg_id: 193738,
        year_published: 2016,
        min_players: 2,
        max_players: 4,
        playtime_minutes: 75,
        publisher: 'Stronghold Games',
        description: 'Deliver cattle across the American frontier.',
        categories: ['Economic', 'Animals'],
        mechanics: ['Deck Building', 'Hand Management'],
        rank: 10,
        rating: 8.2,
        num_ratings: 13000,
        thumbnail_url: null,
        summary: null,
        cached_at: null,
        created_at: '2023-01-01',
        updated_at: '2023-01-01',
        ranking: null,
      },
    ],
  },
};
